name: Release Workflow

on:
  push:
    tags:
      - "v*" # Triggers the workflow when a tag starting with 'v' is pushed

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write # Allows the action to create and update releases

    steps:
      # Step 1: Checkout the repository
      - name: Checkout Repository
        uses: actions/checkout@v3

      # Step 2: Download all artifacts
      - name: Download Artifacts
        uses: actions/download-artifact@v3
        with:
          path: ./artifacts # Download artifacts to a specific directory

      # Step 3: List the downloaded artifacts to verify their paths
      - name: List Downloaded Artifacts
        run: ls -R ./artifacts

      # Step 4: Move artifacts to the root directory for easier reference
      - name: Move Artifacts to Root
        run: |
          mv ./artifacts/xpctl-linux-x86_64.zip .
          mv ./artifacts/xpctl-macos-arm64.zip .
          mv ./artifacts/xpctl-windows-x86_64.zip .

      # Step 5: Create a GitHub release
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.ref }} # Uses the pushed tag as the release tag
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          files: |
            ./xpctl-linux-x86_64.zip
            ./xpctl-macos-arm64.zip
            ./xpctl-windows-x86_64.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
